navbar:
  # 导航栏菜单项
  menu:
    Home: /
    Archives: /archives
    Categories: /categories
    Tags: /tags
    About: /about
  # 导航栏右侧的链接
  links:
    GitHub: 'https://github.com/ddmcc/ddmcc.github.io'
    Download on GitHub:
      icon: fab fa-github
      url: 'https://github.com/ddmcc/ddmcc.github.io'

logo:
  text: jiangrz

article:
  update_time: auto

sidebar:
  left:
    sticky: false
  right:
    sticky: true

widgets:
  - type: recent_posts
    position: right
  - type: categories
    position: right

comment:
  type: gitalk
  client_id: dae41ffb8c8e11287ad0
  client_secret: 2e2acba40e8060cbac419bae13b068ab92a539ab
  repo: ddmcc.github.io
  owner: ddmcc
  admin:
    - ddmcc
  per_page: 20                    # 可选填
  distraction_free_mode: false    # 可选填
  pager_direction: last           # 可选填
  create_issue_manually: false    # 可选填
  proxy:                          # 可选填
  flip_move_options:              # 可选填
  enable_hotkey: true             # 可选填
  language: zh-CN                 # 可选填

search:
  # Name of the search plugin
  type: insight